### ISSUE TITLE
vaadin-combo-box-light on-change not fired

### ISSUE THREAD

**Issue by kedigby** [gatanaso/multiselect-combo-box#14]
Hi Goran

I've struggled to get the multiselect-combo-box to work. I've attempted to debug and have noticed that the _comboBoxValueChanged never gets fired so wondered if there was a dependency / version issue with vaadin-combo-box-light?

I have created and empty project and added the multiselect-combo-box, which demonstrates the issue:  [https://github.com/kedigby/multiselect-combo-box-demo](multiselect-combo-box-demo)

**Comment by gatanaso** [comment]
Hi @kedigby 

Thank you for reporting this issue. It was caused by an issue in the `vaadin-combo-box`: https://github.com/vaadin/vaadin-combo-box/issues/792, which was fixed today and a new version was released (https://github.com/vaadin/vaadin-combo-box/releases/tag/v4.2.7).

I will be updating the dependent version and releasing a new version of `multiselect-combo-box` over the weekend.

Kind regards,
Goran
