### ISSUE TITLE
Problem with compatibility mode on

### ISSUE THREAD

**Issue by DuffMck** [gatanaso/multiselect-combo-box#53]
Hi,

I'm working with Vaadin 14 with compatibility mode on, and I've the problem that without errors in console, the component doesn't appear in the UI.

Can you suggest me any workaround?

Thanks

**Comment by gatanaso** [comment]
Hi @DuffMck ,

This issue is for the Java wrapper of this component: https://github.com/gatanaso/multiselect-combo-box-flow :)

>I'm working with Vaadin 14 with compatibility mode on, and I've the problem that without errors in console, the component doesn't appear in the UI.

> Can you suggest me any workaround?

Which version of the component are you using? For Vaadin 14 compatibility / bower mode you should use versions `1.x.x` of which the latest is `1.0.1`. 

Please note that the compatibility/bower versions are not kept up to date with their npm mode counterparts, so I suggest you update to using Vaadin 14 in npm mode if possible.

Hope this helps,
Goran

**Comment by DuffMck** [comment]
Thanks, I hope to be able to migrate as soon as possible
